'use strict';
const CFG=window.AI_LMS_CONFIG||{};let credential='';let data=null;let timer={minutes:90,remaining:5400,id:null,running:false};
const $=id=>document.getElementById(id);const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
function jsonp(action,payload={}){return new Promise((resolve,reject)=>{if(!CFG.API_URL)return reject(new Error('尚未設定 API_URL'));const cb='lms_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const q=new URLSearchParams({action,callback:cb,credential,...payload});const t=setTimeout(()=>done(new Error('API 連線逾時')),15000);function done(err,val){clearTimeout(t);delete window[cb];s.remove();err?reject(err):resolve(val)}window[cb]=r=>done(null,r);s.onerror=()=>done(new Error('無法連線 GAS Web App'));s.src=CFG.API_URL+'?'+q.toString();document.head.appendChild(s)})}
async function api(action,payload={}){const r=await jsonp(action,{payload:JSON.stringify(payload)});if(!r?.ok)throw new Error(r?.error||'API 操作失敗');return r.data}
function initGoogle(){if(!CFG.GOOGLE_CLIENT_ID){$('configWarning').classList.remove('hidden');$('configWarning').innerHTML='<strong>尚缺 Google Client ID。</strong><br>完成 SETUP.md 的 Google OAuth 設定後，把 Client ID 填入 config.js。';$('loginMessage').textContent='前端已完成，但登入功能尚待設定。';return}if(!window.google?.accounts?.id){setTimeout(initGoogle,500);return}google.accounts.id.initialize({client_id:CFG.GOOGLE_CLIENT_ID,callback:handleCredential,auto_select:false});google.accounts.id.renderButton($('googleButton'),{theme:'outline',size:'large',shape:'pill',text:'signin_with',width:320});$('loginMessage').textContent='請使用 Google 帳號登入。'}
async function handleCredential(r){credential=r.credential;$('loginMessage').textContent='登入成功，正在載入個人學習資料…';try{await loadDashboard();$('loginScreen').classList.add('hidden');$('appShell').classList.remove('hidden')}catch(e){$('loginMessage').textContent='載入失敗：'+e.message}}
async function loadDashboard(){document.body.classList.add('loading');try{data=await api('bootstrap');renderAll()}finally{document.body.classList.remove('loading')}}
function renderAll(){const u=data.user,s=data.stats,p=data.currentPlan;$('userName').textContent=u.name||u.email;$('userEmail').textContent=u.email;$('statCompleted').textContent=`${s.completedDays} / ${data.plan.length}`;$('statStreak').textContent=`${s.streakDays} 天`;$('statMinutes').textContent=`${s.totalMinutes} 分`;$('statPortfolio').textContent=s.portfolioCount;$('scheduleText').textContent=s.completedDays>=data.plan.length?'20 天計畫已完成，可持續更新作品集與能力報告。':`目前進行 DAY ${String(p.day_no).padStart(2,'0')}；依工作日排程為 ${p.schedule_date||'今日'}。`;renderToday();renderRoadmap();renderPortfolio();renderReport(data.report)}
function renderToday(){const p=data.currentPlan,r=data.currentRecord||{};if(!p)return;$('dayBadge').textContent=`DAY ${String(p.day_no).padStart(2,'0')} · ${p.phase}`;$('scheduledDate').textContent=p.schedule_date||'';$('todayTitle').textContent=p.title;$('todaySummary').textContent=p.summary;$('todayMinutes').textContent=`${r.planned_minutes||p.default_minutes} 分鐘`;$('todayTool').textContent=p.tool;$('todayDeliverable').textContent=p.deliverable;$('learningPoints').innerHTML=(p.points||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('caseText').textContent=p.case_text;$('promptText').textContent=p.practice_prompt;$('outputTask').textContent=p.output_task;$('resultNote').value=r.result_note||'';const checks=data.currentChecklist||[];$('checklist').innerHTML=(p.checklist||[]).map((x,i)=>{const c=checks.find(v=>Number(v.item_no)===i+1);return `<li><label><input type="checkbox" data-check="${i+1}" ${c?.checked?'checked':''}><span>${esc(x)}</span></label></li>`}).join('');updateCheckProgress();$('checkinStatus').textContent=data.todayCheckin?'✓ 今日已打卡':'尚未打卡';$('checkinBtn').disabled=!!data.todayCheckin;timer.minutes=Number(r.planned_minutes||p.default_minutes||90);timer.remaining=timer.minutes*60;$('customMinutes').value=timer.minutes;syncTimer()}
function updateCheckProgress(){const a=[...document.querySelectorAll('[data-check]')];$('checkProgress').textContent=`${a.filter(x=>x.checked).length} / ${a.length}`}
function renderRoadmap(){const rec=new Map((data.records||[]).map(x=>[Number(x.day_no),x]));$('roadmapBody').innerHTML=data.plan.map(p=>{const r=rec.get(Number(p.day_no));const st=r?.status==='completed'?'<span class="status-done">已完成</span>':Number(p.day_no)===Number(data.currentPlan?.day_no)?'<span class="status-current">進行中</span>':'尚未開始';return `<tr><td>DAY ${String(p.day_no).padStart(2,'0')}</td><td><strong>${esc(p.title)}</strong></td><td>${esc(p.tool)}</td><td>${esc(p.deliverable)}</td><td>${esc(p.schedule_date||'')}</td><td>${st}</td></tr>`}).join('');const pct=Math.round(data.stats.completedDays/data.plan.length*100);$('progressPercent').textContent=pct+'%';$('progressBar').style.width=pct+'%'}
function renderPortfolio(){const arr=data.portfolio||[];$('portfolioGrid').innerHTML=arr.length?arr.map(x=>`<article class="portfolio-item"><small>DAY ${String(x.day_no||'').padStart(2,'0')} · ${esc(x.tools||'')}</small><h3>${esc(x.title)}</h3><p>${esc(x.result)}</p>${x.result_link?`<a href="${esc(x.result_link)}" target="_blank" rel="noopener">查看作品 ↗</a>`:''}</article>`).join(''):'<p class="muted">尚未加入作品。</p>'}
function renderReport(r){if(!r){$('reportContent').innerHTML='<p class="muted">尚未產生報告。完成更多學習後按「更新能力報告」。</p>';return}const scores=[['Prompt',r.prompt_score],['文件',r.document_score],['研究',r.research_score],['資料',r.data_score],['自動化',r.automation_score],['視覺',r.visual_score],['工作流',r.workflow_score]];$('reportContent').innerHTML=`<h3>${esc(data.user.name||data.user.email)}｜AI 能力摘要</h3><p>完成率 ${r.completion_rate}%｜總學習 ${r.total_minutes} 分鐘</p><div class="score-grid">${scores.map(([k,v])=>`<div class="score"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div><div class="report-note"><strong>目前優勢</strong><p>${esc(r.strengths)}</p><strong>能力缺口</strong><p>${esc(r.skill_gaps)}</p><strong>下一步</strong><p>${esc(r.next_steps)}</p></div>`}
async function saveRecord(status='in_progress'){const p=data.currentPlan;const minutes=Number($('customMinutes').value)||p.default_minutes;const result=await api('saveRecord',{day_no:p.day_no,planned_minutes:minutes,actual_minutes:Math.max(0,Math.round((minutes*60-timer.remaining)/60)),status,result_note:$('resultNote').value.trim()});$('saveMessage').textContent=status==='completed'?'DAY 已完成並同步到 Google Sheet。':'今日進度已同步到 Google Sheet。';await loadDashboard();return result}
function formatTime(s){return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(v).padStart(2,'0')).join(':')}function syncTimer(){$('timerDisplay').textContent=formatTime(timer.remaining);$('timerToggle').textContent=timer.running?'暫停':'開始'}function stopTimer(){if(timer.id)clearInterval(timer.id);timer.id=null;timer.running=false;syncTimer()}
$('checklist').addEventListener('change',async e=>{const box=e.target.closest('[data-check]');if(!box)return;updateCheckProgress();try{await api('saveChecklist',{day_no:data.currentPlan.day_no,item_no:Number(box.dataset.check),item_text:data.currentPlan.checklist[Number(box.dataset.check)-1],checked:box.checked})}catch(err){alert(err.message)}});$('checkinBtn').onclick=async()=>{try{await api('checkin',{day_no:data.currentPlan.day_no});await loadDashboard()}catch(e){alert(e.message)}};$('saveDayBtn').onclick=()=>saveRecord('in_progress').catch(e=>alert(e.message));$('completeDayBtn').onclick=()=>saveRecord('completed').catch(e=>alert(e.message));$('addPortfolioBtn').onclick=async()=>{try{await api('savePortfolio',{day_no:data.currentPlan?.day_no||20,title:$('portfolioTitle').value.trim(),tools:$('portfolioTools').value.trim(),result:$('portfolioResult').value.trim(),result_link:$('portfolioLink').value.trim()});['portfolioTitle','portfolioTools','portfolioResult','portfolioLink'].forEach(id=>$(id).value='');await loadDashboard()}catch(e){alert(e.message)}};$('generateReportBtn').onclick=async()=>{try{const r=await api('generateReport');data.report=r;renderReport(r)}catch(e){alert(e.message)}};document.querySelectorAll('[data-minutes]').forEach(b=>b.onclick=()=>{if(timer.running)return;timer.minutes=Number(b.dataset.minutes);timer.remaining=timer.minutes*60;$('customMinutes').value=timer.minutes;document.querySelectorAll('[data-minutes]').forEach(x=>x.classList.toggle('active',x===b));syncTimer()});$('applyMinutes').onclick=()=>{const m=Math.max(10,Math.min(360,Number($('customMinutes').value)||90));stopTimer();timer.minutes=m;timer.remaining=m*60;syncTimer()};$('timerToggle').onclick=()=>{if(timer.running){stopTimer();return}timer.running=true;syncTimer();timer.id=setInterval(()=>{timer.remaining--;syncTimer();if(timer.remaining<=0)stopTimer()},1000)};$('timerReset').onclick=()=>{stopTimer();timer.remaining=timer.minutes*60;syncTimer()};$('logoutBtn').onclick=()=>{credential='';data=null;google?.accounts?.id?.disableAutoSelect();$('appShell').classList.add('hidden');$('loginScreen').classList.remove('hidden');$('loginMessage').textContent='已登出，請重新使用 Google 帳號登入。'};
window.addEventListener('load',initGoogle);
